name: Build Rules

# ============================================
# 触发条件
# ============================================

on:

  # 手动运行
  workflow_dispatch:

  # 定时运行
  schedule:

    # 每6小时运行一次
    #
    # GitHub Actions 使用 UTC 时间
    #
    # 北京时间：
    # UTC+8
    #
    # 例如：
    # 00:00 UTC = 08:00 上海时间
    #
    - cron: "0 */6 * * *"



# ============================================
# 最小权限原则
# ============================================

permissions:
  contents: write



jobs:

  build:

    runs-on: ubuntu-latest



    steps:

      # ======================================
      # 拉取仓库
      # ======================================

      - name: Checkout Repository

        uses: actions/checkout@v4

        with:

          # 不保留 git token 到 git config
          persist-credentials: false



      # ======================================
      # 安装 Python
      # ======================================

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"



      # ======================================
      # 安装依赖
      # ======================================

      - name: Install Dependencies

        run: |

          python -m pip install --upgrade pip

          pip install requests pyyaml



      # ======================================
      # 设置上海时区
      # ======================================

      - name: Set Timezone

        run: |

          sudo timedatectl set-timezone Asia/Shanghai



      # ======================================
      # 执行 action 目录所有 py
      # ======================================

      - name: Run Python Scripts

        run: |

          for file in action/*.py
          do

            echo "===================================="
            echo "Running: $file"
            echo "===================================="

            python "$file"

          done



      # ======================================
      # Git 提交
      # ======================================

      - name: Commit Changes

        run: |

          git config --local user.name "github-actions[bot]"

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "Auto Update Rules"



      # ======================================
      # Push 回仓库
      # ======================================

      - name: Push Changes

        uses: ad-m/github-push-action@master

        with:

          github_token: ${{ github.token }}

          branch: main
